### ISSUE TITLE
init_os.sh执行错误

### ISSUE THREAD

**Issue by Winsweeter** [Horacehxw/Ziggo-CaaS-Switch#2]
执行sh init_os.sh文件时也遇到如下图所示问题，请问该如何解决?
': not a valid identifier `hostname
hostname is set to
init_os.sh: line 7: $'\r': command not found
': not a valid identifier `ipAddr7.
ip address is set to 192.168.137.
init_os.sh: line 11: $'\r': command not found
': not a valid identifier: `macAddr
mac address is set to 00:0A:35:00:
init_os.sh: line 15: $'\r': command not found
: No such file or directoryk/interfaces
: No such file or directoryk/interfaces
: No such file or directoryk/interfaces
: No such file or directoryk/interfaces
: No such file or directoryk/interfaces
: No such file or directoryk/interfaces
init_os.sh: line 22: $'\r': command not found
###### Restart Network #######
Usage: /etc/init.d/networking {start|stop}
init_os.sh: line 25: $'\r': command not found
###### Setting startup script #######
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
domain mshome.net
nameserver 192.168.137.1
nameserver 8.8.8.8
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
cp /etc/resolvconf/resolv.conf.d/head /etc/resolv.conf
sudo ldconfig
insmod /lib/modules/5.4.0-xilinx-v2020.1/extra/dma-proxy.ko
ln: target ''$'\r': No such file or directory
init_os.sh: line 36: $'\r': command not found
: No such file or directoryrofile

![img1](https://github.com/Horacehxw/Ziggo-CaaS-Switch/assets/120151121/923414f4-22dd-4c67-a1e0-e4f7cba53052)
![img2](https://github.com/Horacehxw/Ziggo-CaaS-Switch/assets/120151121/d32789c2-e514-451d-ba89-b8d6b69e43b6)

**Comment by ycdfwzy** [comment]
您好，这是编码格式的问题，我们已经提交了一个pull request。
你也可以自行把init_os.sh从CRLF改成LF。

**Comment by Winsweeter** [comment]
有个小问题，https://github.com/Horacehxw/Ziggo-CaaS-Switch 固化程序只是交换机部分的代码吗？

**Comment by ycdfwzy** [comment]
是的

**Comment by Winsweeter** [comment]
taskset -c 1 ./time_sync  将进程绑定到特定的 CPU 核心时出现了问题，如附图img3所示，请问该如何解决呢
![Uploading img3.png…]()

**Comment by Winsweeter** [comment]
> 是的

那么device设备上是部署哪个代码呢？Switch or Toolkit ?

**Comment by Winsweeter** [comment]
谈一下我对文档阅读顺序的浅薄理解，分三步：首先是固化程序的烧录和硬件初始化配置（Hardware: FPGA bitstream & Petalinux system rootfs for TSN Evaluation Toolkit 和Hardware: Build the CaaS TSNPerf）；然后是是时间同步测试（Time Sync + Config for CaaS Switches和Time Sync + Pkt Gen for CaaS TSNPerf）；最后是测试平台测试（互联互通测试TestBed搭建流程），请问是这样的逻辑吗

**Comment by Winsweeter** [comment]
> > 是的
> 
> 那么device设备上是部署哪个代码呢？Switch or Toolkit ?

首先对贵团队的工作表示respect，因为从"Hardware: Build the CaaS TSNPerf"文档 6. SD card partition and copy file 部分介绍部分还是给的aaS-TSN Switch v2.0 Public固化程序的链接，且该文档的描述还是针对 CaaS Switch的，说实话文档中有些内容的表述感觉很容易使使用者迷惑呢？所以说CaaS TSNPerf部分是需要自己在petalinux 2020.1中生成BOOT.BIN boot.scr image.ub rootfs.tar.gz这四个文件吗？

**Comment by Winsweeter** [comment]
taskset -c 1 ./time_sync -l t 命令执行错误：Cannot open GPIO to export it
./switch_config 命令执行错误：Invalid UIO device file:/dev/uio0! Segmentation fault (core dumped)

请问这两个时间同步错误该如何解决呢？

![Uploading img4.png…]()

**Comment by ycdfwzy** [comment]
> 谈一下我对文档阅读顺序的浅薄理解，分三步：首先是固化程序的烧录和硬件初始化配置（Hardware: FPGA bitstream & Petalinux system rootfs for TSN Evaluation Toolkit 和Hardware: Build the CaaS TSNPerf）；然后是是时间同步测试（Time Sync + Config for CaaS Switches和Time Sync + Pkt Gen for CaaS TSNPerf）；最后是测试平台测试（互联互通测试TestBed搭建流程），请问是这样的逻辑吗

你的理解是对的

**Comment by ycdfwzy** [comment]
你的两个回复，里面的图片我这里看不到 @Winsweeter

**Comment by Winsweeter** [comment]
王老师您好，首先表示感谢，此外，图片上传了几次都不行，我想加一下咱们项目的交流群或者是您的联系方式交流一下。
想快速的把咱这个项目熟悉一下，麻烦您了。

-----原始邮件-----
发件人:"Wang Zeyu" ***@***.***>
发送时间:2024-02-26 15:17:19 (星期一)
收件人: Horacehxw/Ziggo-CaaS-Switch ***@***.***>
抄送: "Yingfei Yao" ***@***.***>, Mention ***@***.***>
主题: Re: [Horacehxw/Ziggo-CaaS-Switch] init_os.sh执行错误 (Issue #2)






你的两个回复，里面的图片我这里看不到 @Winsweeter
